const TAG = 'GLOB_'
export const API_LOADING_START = TAG + 'API_LOADING_START';
export const API_LOADING_STOP = TAG + 'API_LOADING_STOP';
export const IS_INTERNET_CONNECTED = TAG + 'IS_INTERNET_CONNECTED';
